### ISSUE TITLE
Migrate C# completer to OmniSharp-Roslyn

### ISSUE THREAD

**Issue by micbou** [ycm-core/ycmd#1082]
The C# completer currently relies on [OmniSharpServer](https://github.com/OmniSharp/omnisharp-server) which is not maintained anymore. [OmniSharp-Roslyn](https://github.com/OmniSharp/omnisharp-roslyn) should be used instead. PR https://github.com/Valloric/ycmd/pull/885 implements this but there are some issues with it:
 - keep support for OmniSharpServer: we don't want to maintain two backends for one language;
 - add support for Cygwin: something else we don't want to maintain;
 - do not use [LSP](https://microsoft.github.io/language-server-protocol/) which could simplify things (or maybe not, we are talking about LSP after all);
 - seem abandoned.

**Comment by bstaletic** [comment]
The problem with Roslyn is that it doesn't support FixIts and that's one of the blockers.

**Comment by micbou** [comment]
I completely missed that. I suppose we need to wait for PR https://github.com/OmniSharp/omnisharp-roslyn/pull/1076 then.

**Comment by bstaletic** [comment]
Woah! Finaly... however, they didn't respond to @mispencer's question about if they plan to support FixIts when he asked. :/

**Comment by ohjames** [comment]
The version of OmniSharp that works with YouCompleteMe is so ancient as to be useless.

Are fixits really needed? If not, are they as useful as not being on an ancient version of C#?

Given that many other extensions manage to use OmniSharp-roslyn I'm thinking there's got to be a more pragmatic solution here.

**Comment by bstaletic** [comment]
> Are fixits really needed? I don't have a clue what they are. If not, are they as useful as not being on an ancient version of C#?

There is a `:YcmCompleter FixIt` command that can fix some syntax errors, like a missing semicolon.

Since OmniSharp/omnisharp-roslyn#1076 doesn't seem like it will be merged any time soon, I'm starting to think that FixIts are an acceptable loss at this point.

Just a note, the LSP interface for Roslyn was in a terrible state last time I checked ad if it is still the case, we shouldn't use it.

**Comment by ohjames** [comment]
@bstaletic The current OmniSharp server isn't using LSP either, so wouldn't it be okay to migrate to the roslyn version without double-migrating also to LSP? Feels like a simpler more incremental change? When it comes to completion via LSP there's a lot of really great solutions, I think the reason a lot of people still use YCM is precisely because it has such great support for so many langauges, many not yet covered by LSP.

**Comment by ohjames** [comment]
Yep I've been experimenting with OmniSharp-Roslyn's LSP implementation, a few things work well but many things don't work at all. The upgrade path from Omnisharp to Omnisharp-roslyn isn't much work, I think it'd be the only thing capable of delivering really great code completion to YCM (and vim/neovim) without too much effort. C# code completion might remain out of the realm of possibility for vim users for some time unless we make a pragmatic stop-gap solution with what we have.

**Comment by ohjames** [comment]
Anyway this is something I'm happy to work on, I totally understand if you don't want it in the mainline YCM repository. If I have to maintain a fork for a short time to get decent C# completion without having to use VSCodeVim then I'm also happy to do that. Hopefully the LSP support will progress quickly enough that whatever happens can be trashed fairly quickly. For me at least, it'd be worth my effort so that I can use my favourite editor with the Unity project I'm working with for the next few months.

**Comment by puremourning** [comment]
I suspect that losing FixIts is not the end of the world. @mispencer maintained the C# support, so I assume their opinion counts too, but provided the server is maintained and stable and the tests are adequate, i would be happy to use roslyn on the basis that is what's actively developed and supported by MS, right ?

Does anyone know what VSCode uses for non-windows c# support? When i looked at it for vimspector, it looked like they use mono + proprietary licensed MS stuff where the license basically says "can't be used outside of VScode". I take it they are not using omnisharp ?

**Comment by bstaletic** [comment]
Roslyn is what is maintained and supported. To summarize my thoughts:

- FixIts aren't worth keeping legacy server supported and thus making YCM's C# completer useless for the ever growing number of users.
- Cygwin support would add a ton of complexity and supporting it means actually making all completers work with it, plus running another appveyor job. Without one of the core maintainers using and actively supporting cygwin, I don't think it is worth the trouble.
- Roslyn LSP support is not the way to go.
- While at this point there is a case of two servers for a single language, I'd still want to avoid that as much as possible.

**Comment by mispencer** [comment]
If there is interest, I can rework and resubmit my earlier PR without the Cygwin support or legacy Omnisharp support.

I don't personally use Cygwin anymore (like many people I suspect, I have migrated to WSL). So I am ok with removing the Cygwin logic from my earlier PR. I am also ok with removing the legacy Omnisharp support entirely at this point. Unlike two years ago, I don't need support for legacy code.

Last I checked (which was quite awhile ago), VS Code is using OmniSharp though the [Omnisharp-vscode extension](https://github.com/OmniSharp/omnisharp-vscode).

**Comment by bstaletic** [comment]
I'd be completely fine with migrating to Roslyn without cygwin support and with legacy server being dropped completely.

**Comment by Valloric** [comment]
I'd be willing to lose plenty of existing features to update to the latest Roslyn parser. As has been stated here, our existing C# support is pretty out of date at this point.

**Comment by mispencer** [comment]
I created https://github.com/Valloric/ycmd/pull/1209 for this.

**Comment by bstaletic** [comment]
Done in #1274.
