### ISSUE TITLE
GoToDefinition/GoToDeclaration behaviour in python

### ISSUE THREAD

**Issue by yangyangxcf** [ycm-core/ycmd#1359]
At present after #1343, both `GoToDefinition` and `GoToDeclaration` does `jedi`'s `Script.goto_definitions()`, which jumps, for example, from
```python
@classmethod
def f(cls):
    pass
f|
```
to some `builtins.pyi`. And from
```python
@some_decorator
def f():
    pass
f|
```
to where `some_decorator` is defined.
I understand the second case is useful sometimes, though there are when one doesn't care the decorators (which I believe is even most cases), but I couldn't really think of some practical use case of the first one. 
Notice that `jedi` has a `follow_imports` parameter for `goto_assignments` which jumps to `f` in both cases so acts differently and is really useful.
So could we just switch `GoToDeclaration` back to `goto_assignments(follow_imports=True)`?

**Comment by bstaletic** [comment]
So the reason why #1343 (`gooto_assignments(follow_imports=False)`) was reverted is because, depending on where you execute `GoTo`/`GoToDefinition`/`GoToDeclaration`, it could do 3 thing:

- Work as expected.
- Run into an infinite loop, as in https://github.com/ycm-core/YouCompleteMe/issues/3458
- Run into a jedi bug, as in https://github.com/ycm-core/ycmd/issues/1341#issuecomment-543135660

The reason why `goto_assignments(follow_imports=False)` because it also goes "through" an import statement when there's an alias, as in `import foo as bar`. This was discussed in https://github.com/ycm-core/ycmd/pull/1200. The consensus was that it is just as confusing as the current behaviour, only in different places.

Unfortunately, the current behaviour isn't ideal either and that's why #1200 and #1275 were made.

In the end, the choice to rever #1275 in #1343 was chose because it doesn't cause vim to hang in certain cases, forcing users to kill YCM.

> So could we just switch GoToDeclaration back to goto_assignments(follow_imports=True)?

No, but we definitely are aware of the problem and are open for ideas.

**Comment by yangyangxcf** [comment]
Thanks for the clarafication. I will close the issue. :)

**Comment by bstaletic** [comment]
Let's reopen, since there really is a problem to be solved. If nothing, it will keep reminding us of the existing problem.
