### ISSUE TITLE
Support UTF-8 for the LSP protocol 

### ISSUE THREAD

**Issue by XVilka** [ycm-core/ycmd#1366]
See the lengthy discussion here: https://github.com/microsoft/language-server-protocol/issues/376

It seems that ycmd is one of a few that uses UTF-16 https://github.com/Avi-D-coder/lsp-range-unit-survey

Would be nice if it will have UTF-8 support as well, at least optionally.

**Comment by bstaletic** [comment]
You can find everything I'm about to say in that giant mess of a thread, but I'll explain our position here as well. Ycmd does use UTF-8 for everything except LSP. We would like to use UTF-8 everywhere, but... The thing is, currently, ycmd conforms to the protocol, unlike the "UTF-8 only" servers/clients. Supporting two encodings for LSP is out of the question considering the number of active contributors. That leaves only one option - first the protocol needs to change, then ycmd can follow. Like stated many times in that thread, maintaining UTF-16 support didn't come for free for us. Maintaining another encoding, plus an encoding negotiation is not something we want to do, unless the protocol forces us.

As for being one of the few who use UTF-16, I doubt it. The survey you are referencing was made back when the issue was heated, the servers and clients were few and people hoped that the encoding of the protocol could be changed "soon". Since then, there was another survey that painted a different picture. UTF-8 was rare, responses were fewer, "support UTF-16" bug reports have been resolved and most importantly Microsoft clearly doesn't want to change the specifications and move away from UTF-16. Also, A LOT of servers test only against before, which uses UTF-16.

**Comment by XVilka** [comment]
Some sane projects, like clangd, chose not to conform to the bad standard (UTF-16 is a cancer after all), if enough projects will support UTF-8 as an option at least, we can force the Microsoft's hand to change the decision.

**Comment by bstaletic** [comment]
Unlike ycmd, clangd has much more manpower behind it and can afford to maintain two separate encodings. UTF-16 is bad, but not conforming to the protocol is worse.

Oh, also, clangd does conform to the protocol - by default it will use UTF-16.

**Comment by XVilka** [comment]
Ok, anyway thanks for your answer! Hope you will find more contributors in time!

**Comment by bstaletic** [comment]
Thanks for understanding.

**Comment by puremourning** [comment]
For the record, this isn't really about manpower exactly. If the specification said we need to support multiple encodings, then we would. This is about it being pointless to have a standard specification if server vendors decide not to implement the specification.

our standpoint is that ycmd implements the specification and any server which does not is broken.
