### ISSUE TITLE
"Implement didChangeWatchedFiles support" hangs on YouCompleteMe install

### ISSUE THREAD

**Issue by rjmccabe3701** [ycm-core/ycmd#1421]
Commit 6f43da6b28bd698f88ad2afebebb63b429e40bee fails to clone ``git://github.com/mitsuhiko/flask-sphinx-themes.git`` behind my corporate firewall.

I get an error when I run:

```
nvim \
    "+PlugInstall" \
    "+PlugClean" \
    "+qall"
```

With a ``Plug 'valloric/youcompleteme'`` in my [vimrc](https://github.com/rjmccabe3701/linux_config_custom/blob/master/dot_files/myvimrc_plugins#L5):

![image](https://user-images.githubusercontent.com/463534/79136088-0ca56400-7d76-11ea-8190-acb8451db981.png)

The issue is in the [flash-sphinx-theme](https://github.com/gorakhargosh/pathtools/blob/master/.gitmodules#L3) repo.  

I created this [pull request](https://github.com/gorakhargosh/pathtools/pull/9) for that repository, but it seems that it hasn't had any activity in the last few years.

**Comment by puremourning** [comment]
> Commit 6f43da6 fails to clone git://github.com/mitsuhiko/flask-sphinx-themes.git behind my corporate firewall.

That seems to be a problem of your environment rather than a problem with ycmd.

I suspect the reason is that they are using git: as the submodule path and your firewall (like the one at my work) only allows https. You can force all git: to use https with some .gitconfig magic:

e.g. `git config --global url."https://".insteadOf git://`

Does that work ?

**Comment by rjmccabe3701** [comment]
Well I'll be darned.  I didn't know you could do that.  You learn something new everyday.  Thanks!

**Comment by puremourning** [comment]
YW. I have the _exact_ same problem.
