### ISSUE TITLE
YCM shows C++ warnings in a C file when ymc_extra_conf.py is active

### ISSUE THREAD

**Issue by coldspark29** [ycm-core/ycmd#1492]
Well the headline basically describes the problem. I am working in a C code and get the following message. Is this normal?

``Warning: ISO C++11 does not allow conversion from string literal to 'char *'``

I get no warnings when I compile the code with gcc.

My ycm_extra_conf.py is located at /home and I think I just copied the standard file. I have honestly not had the time to extensively read the documentation. Is it required to change this file for every project? 

```
# This file is NOT licensed under the GPLv3, which is the license for the rest
# of YouCompleteMe.
#
# Here's the license text for this file:
#
# This is free and unencumbered software released into the public domain.
#
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# For more information, please refer to <http://unlicense.org/>

from distutils.sysconfig import get_python_inc
import os
import platform
import os.path as p
import subprocess

DIR_OF_THIS_SCRIPT = p.abspath( p.dirname( __file__ ) )
DIR_OF_THIRD_PARTY = p.join( DIR_OF_THIS_SCRIPT, 'third_party' )
DIR_OF_WATCHDOG_DEPS = p.join( DIR_OF_THIRD_PARTY, 'watchdog_deps' )
SOURCE_EXTENSIONS = [ '.c', '.cxx', '.cc', '.cpp', '.m', '.mm' ]

database = None

# These are the compilation flags that will be used in case there's no
# compilation database set (by default, one is not set).
# CHANGE THIS LIST OF FLAGS. YES, THIS IS THE DROID YOU HAVE BEEN LOOKING FOR.
flags = [
'-Wall',
'-Wextra',
'-Werror',
'-Wno-long-long',
'-Wno-variadic-macros',
'-fexceptions',
'-DNDEBUG',
# You 100% do NOT need -DUSE_CLANG_COMPLETER and/or -DYCM_EXPORT in your flags;
# only the YCM source code needs it.
'-DUSE_CLANG_COMPLETER',
'-DYCM_EXPORT=',
# THIS IS IMPORTANT! Without the '-x' flag, Clang won't know which language to
# use when compiling headers. So it will guess. Badly. So C++ headers will be
# compiled as C headers. You don't want that so ALWAYS specify the '-x' flag.
# For a C project, you would set this to 'c' instead of 'c++'.
'-x',
'c++',
'-isystem',
'cpp/pybind11',
'-isystem',
'cpp/whereami',
'-isystem',
'cpp/BoostParts',
'-isystem',
get_python_inc(),
'-isystem',
'cpp/llvm/include',
'-isystem',
'cpp/llvm/tools/clang/include',
'-I',
'cpp/ycm',
'-I',
'cpp/ycm/ClangCompleter',
'-isystem',
'cpp/ycm/tests/gmock/gtest',
'-isystem',
'cpp/ycm/tests/gmock/gtest/include',
'-isystem',
'cpp/ycm/tests/gmock',
'-isystem',
'cpp/ycm/tests/gmock/include',
'-isystem',
'cpp/ycm/benchmarks/benchmark/include',
]

# Clang automatically sets the '-std=' flag to 'c++14' for MSVC 2015 or later,
# which is required for compiling the standard library, and to 'c++11' for older
# versions.
if platform.system() != 'Windows':
  flags.append( '-std=c++11' )


# Set this to the absolute path to the folder (NOT the file!) containing the
# compile_commands.json file to use that instead of 'flags'. See here for
# more details: http://clang.llvm.org/docs/JSONCompilationDatabase.html
#
# You can get CMake to generate this file for you by adding:
#   set( CMAKE_EXPORT_COMPILE_COMMANDS 1 )
# to your CMakeLists.txt file.
#
# Most projects will NOT need to set this to anything; you can just change the
# 'flags' list of compilation flags. Notice that YCM itself uses that approach.
compilation_database_folder = ''


def IsHeaderFile( filename ):
  extension = p.splitext( filename )[ 1 ]
  return extension in [ '.h', '.hxx', '.hpp', '.hh' ]


def FindCorrespondingSourceFile( filename ):
  if IsHeaderFile( filename ):
    basename = p.splitext( filename )[ 0 ]
    for extension in SOURCE_EXTENSIONS:
      replacement_file = basename + extension
      if p.exists( replacement_file ):
        return replacement_file
  return filename


def PathToPythonUsedDuringBuild():
  try:
    filepath = p.join( DIR_OF_THIS_SCRIPT, 'PYTHON_USED_DURING_BUILDING' )
    with open( filepath ) as f:
      return f.read().strip()
  except OSError:
    return None


def Settings( **kwargs ):
  # Do NOT import ycm_core at module scope.
  import ycm_core

  global database
  if database is None and p.exists( compilation_database_folder ):
    database = ycm_core.CompilationDatabase( compilation_database_folder )

  language = kwargs[ 'language' ]

  if language == 'cfamily':
    # If the file is a header, try to find the corresponding source file and
    # retrieve its flags from the compilation database if using one. This is
    # necessary since compilation databases don't have entries for header files.
    # In addition, use this source file as the translation unit. This makes it
    # possible to jump from a declaration in the header file to its definition
    # in the corresponding source file.
    filename = FindCorrespondingSourceFile( kwargs[ 'filename' ] )

    if not database:
      return {
        'flags': flags,
        'include_paths_relative_to_dir': DIR_OF_THIS_SCRIPT,
        'override_filename': filename
      }

    compilation_info = database.GetCompilationInfoForFile( filename )
    if not compilation_info.compiler_flags_:
      return {}

    # Bear in mind that compilation_info.compiler_flags_ does NOT return a
    # python list, but a "list-like" StringVec object.
    final_flags = list( compilation_info.compiler_flags_ )

    # NOTE: This is just for YouCompleteMe; it's highly likely that your project
    # does NOT need to remove the stdlib flag. DO NOT USE THIS IN YOUR
    # ycm_extra_conf IF YOU'RE NOT 100% SURE YOU NEED IT.
    try:
      final_flags.remove( '-stdlib=libc++' )
    except ValueError:
      pass

    return {
      'flags': final_flags,
      'include_paths_relative_to_dir': compilation_info.compiler_working_dir_,
      'override_filename': filename
    }

  if language == 'python':
    return {
      'interpreter_path': PathToPythonUsedDuringBuild()
    }

  return {}


def PythonSysPath( **kwargs ):
  sys_path = kwargs[ 'sys_path' ]

  interpreter_path = kwargs[ 'interpreter_path' ]
  major_version = subprocess.check_output( [
    interpreter_path, '-c', 'import sys; print( sys.version_info[ 0 ] )' ]
  ).rstrip().decode( 'utf8' )

  sys_path[ 0:0 ] = [ p.join( DIR_OF_THIS_SCRIPT ),
                      p.join( DIR_OF_THIRD_PARTY, 'bottle' ),
                      p.join( DIR_OF_THIRD_PARTY, 'cregex',
                              'regex_{}'.format( major_version ) ),
                      p.join( DIR_OF_THIRD_PARTY, 'frozendict' ),
                      p.join( DIR_OF_THIRD_PARTY, 'jedi_deps', 'jedi' ),
                      p.join( DIR_OF_THIRD_PARTY, 'jedi_deps', 'parso' ),
                      p.join( DIR_OF_THIRD_PARTY, 'requests_deps', 'requests' ),
                      p.join( DIR_OF_THIRD_PARTY, 'requests_deps',
                                                  'urllib3',
                                                  'src' ),
                      p.join( DIR_OF_THIRD_PARTY, 'requests_deps',
                                                  'chardet' ),
                      p.join( DIR_OF_THIRD_PARTY, 'requests_deps',
                                                  'certifi' ),
                      p.join( DIR_OF_THIRD_PARTY, 'requests_deps',
                                                  'idna' ),
                      p.join( DIR_OF_WATCHDOG_DEPS, 'watchdog', 'build', 'lib3' ),
                      p.join( DIR_OF_WATCHDOG_DEPS, 'pathtools' ),
                      p.join( DIR_OF_THIRD_PARTY, 'waitress' ) ]

  sys_path.append( p.join( DIR_OF_THIRD_PARTY, 'jedi_deps', 'numpydoc' ) )
  return sys_path
```

**Comment by bstaletic** [comment]
First, don't delete the issue template. Fill it in. Second, I don't see your extra conf, but I'm willing to bet my compiler that you told YCM to treat all files as C++.

**Comment by bstaletic** [comment]
> I think I just copied the standard file.

You copied the file that was tailored for ycmd. It was never intended to be a one-size-fits-all, because that would be absolutely impossible.

> I have honestly not had the time to extensively read the documentation. 

That would have been fine if you had at least read the file you copied.

> Is it required to change this file for every project?

If you don't provide YCM with correct flags, how can you expect YCM to parse your code? You will have to read the docs.

https://github.com/ycm-core/YouCompleteMe/#c-family-semantic-completion

**Comment by coldspark29** [comment]
Well it is just a C file. I don't understand why that is even necessary...

**Comment by bstaletic** [comment]
> Well it is just a C file.

For which you've explicitly told clang to treat it as C++.

> I don't understand why that is even necessary.

How do you expect *any* non-trivial project to get compiled without specific compiler flags?

If "the project" in question is trivial and is only a single file, you could have skipped the extra conf completely. That does require reading the docs...

> Do I have to edit this file every time I want to code in another language?

You do, to the same extent that you need to configure any IDE for the specific project you are working on. Also, the docs mention alternatives to the `.ycm_extra_conf.py`.

> That would be really stupid.

We're not ones who designed C and C++ with so many knobs you can turn. You'll have to complain to the C standard's committee.

**Comment by coldspark29** [comment]
Well I don't need any of this at this point since I am obviously a complete noob who just wants some code completion in his Vim, but when I don't have the ycm_extra_conf, YCM complains with an error notification. That is probably the only reason why I copied the file in the first place. So I did not tell clang anything. If someone did than it was the person who wrote this example file. So there is this line saying "This is important". When I set the C++ there to C, I have the same error. So can you please tell me which line to change instead of lecturing me?

**Comment by puremourning** [comment]
Before responding further please carefully read the YCM code of conduct and the YCM Contributing guide.

**Comment by coldspark29** [comment]
Sorry, I am honestly a little overworked at the moment. I also remember that the last time I asked something here, I felt that my low level of experience was something that no one wants to deal with here. YCM is an awesome tool and I understand that you can not describe it with two sentences, but the documentation is really massive. Even when I do read it, I understand very little.

I now managed to generate a working conf for this project with YCMgenerator. I would still like to change the standard ycm_extra_conf.py to be working with C, as I don't use C++ at all.

**Comment by puremourning** [comment]
I think Boris explained that there is no "standard" YCM extra conf file. There is the one we use for YCM itself, and there are some examples.

That said, if you were to use the clangd completer, then you don't need one at all and for most simple projects, clangd will guess appropriate flags, including I think for C files.

The [section of the README that explains this](https://github.com/ycm-core/YouCompleteMe#option-1-use-a-compilation-database) is fairly clear and includes a minimal example, and links to information on how to generate a compilation database.

Regarding lack of experience, we are absolutely willing to help users with setup and configuration regardless of experience level. I'm truly sorry if you at any point felt otherwise.

We do help users almost daily on our Gitter channel. As our CONTRIBUTING.md says, the issue tracker is not for technical support, it's for bugs and feature requests. Gitter is where we can have a one-to-one conversation which is the most efficient way to solve your issues.

If you're using YCMGenerator, I would suggest that you might be better off with `--clangd-completer` and using something like `bear` (or usually better `compiledb`) to create a compilation database. This will not only work probably better but it will also open up a lot of extra features, like GoToDefintion, signature help and much more.

Regarding being overworked, you're not the only one. Boris and I support this project (and other OSS projects) in our spare time for literally nothing. You can probably imagine that it's not fun for us to support a passive/aggressive or dismissive issue reports particularly where there is clear and adequate documentation. To put it frankly, if users are unwilling to read the documentation (for example) it makes us feel like the user considers their own time more valuable than ours, which with the greatest possible respect, we would probably dispute :) 

Anyway finally regarding documentation, long years of experience have taught us that there are literally 2 things people say about documentation:

* You need to add `<something>` to the documentation otherwise it's impossible to do `....`
* Your documentation is too big, where is the magic go button.

So rock, hard place.

Anyway. Meta over, I'm going to lock this thread as "resolved". Please feel free to chat to us on Gitter if you have other issues which are not clearly bugs or feature requests, and in future please do use the YCM repo (not the ycmd) repo and complete the issue template, as this further reduces the amount of time required to support users.
